{"name": "test_failing_for_report_check", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "api_client = <conftest.ApiClient object at 0x1068ffca0>\n\n    @allure.feature(\"Reporting\")\n    @allure.story(\"Failure reporting\")\n    def test_failing_for_report_check(api_client):\n        \"\"\"\n        This test is designed to fail to demonstrate the reporting hook.\n        (For Exercise 10, this test should be deleted or commented out).\n        \"\"\"\n        log.info(\"--- Starting failing test to check report hook ---\")\n        url = \"https://api.github.com/users/nonexistentuser12345\"\n    \n        with allure.step(\"Requesting a non-existent user\"):\n            response = api_client.get(url)\n            log.info(f\"Response Status Code: {response.status_code}\")\n    \n        with allure.step(\"Asserting a failure\"):\n            # This assertion will fail, triggering the hook in conftest.py\n>           assert response.status_code == 200\nE           assert 404 == 200\nE            +  where 404 = <Response [404]>.status_code\n\ntests/test_github_api.py:86: AssertionError"}, "description": "\n    This test is designed to fail to demonstrate the reporting hook.\n    (For Exercise 10, this test should be deleted or commented out).\n    ", "steps": [{"name": "Requesting a non-existent user", "status": "passed", "start": 1760958056373, "stop": 1760958056556}, {"name": "Asserting a failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code\n", "trace": "  File \"/Users/lpcb/Documents/repos/projeto_api/aula4/solucao/tests/test_github_api.py\", line 86, in test_failing_for_report_check\n    assert response.status_code == 200\n"}, "start": 1760958056556, "stop": 1760958056556}], "attachments": [{"name": "log", "source": "0df9b865-c4b9-4d70-8513-11ddec27bdd8-attachment.txt", "type": "text/plain"}], "start": 1760958056373, "stop": 1760958056558, "uuid": "e2a75da9-6966-4ac4-a247-d4e32aa586eb", "historyId": "d38393613bd20a21b5dc6180a586cb85", "testCaseId": "d38393613bd20a21b5dc6180a586cb85", "fullName": "tests.test_github_api#test_failing_for_report_check", "labels": [{"name": "feature", "value": "Reporting"}, {"name": "story", "value": "Failure reporting"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_github_api"}, {"name": "host", "value": "EU33146031018504-2.local"}, {"name": "thread", "value": "33759-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_github_api"}], "titlePath": ["tests", "test_github_api.py"]}